name: build suss package workflow
on: 
  push:
    branches:
      - dev
jobs:
  build-suss-package:
    runs-on: ubuntu-20.04
    steps:
      - name: check out code from repo
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: install package dependencies
        run: |
          zip -R outp.zip printdir.py

      - name: run python code
        run: |
          python3.10 printdir.py

      # - name: Generate release tag
      #   uses:  amitsingh-007/next-release-tag@v2.2.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
                  

      - name: create release
        uses:  rymndhng/release-on-push-action@master
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          bump_version_scheme: patch
          tag_prefix: v
          
      
      - name: check output params
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
      
       
          # tag_name: ${{ env.release_tag }}
          # release_name: Release ${{ env.release_tag }}
          # prerelease: false
          # draft: false
          
          #artifacts: outp.zip
      
          #files: "dist/suss-0.0.1.tar.gz"
      